name: Release

on:
  release:
    types: [created]

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact: ff
          - os: macos-latest
            target: x86_64-apple-darwin
            artifact: ff
          - os: macos-latest
            target: aarch64-apple-darwin   # Apple Silicon
            artifact: ff
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact: ff.exe

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
      - run: cargo build --release --target ${{ matrix.target }}
      - uses: softprops/action-gh-release@v1
        with:
          files: target/${{ matrix.target }}/release/${{ matrix.artifact }}